In [2]:
import pandas as pd

data = pd.read_csv("performance_survey_cleaned.csv")
data.head()

,condition,wer,num_signgloss,intended_meaning,asl_gloss,error_asl_gloss,error_intended_meaning,original_word,misclassified_word
0,1,0.111,9,"My family is small. It consists of my mother, ...",MY FAMILY SMALL MOTHER FATHER YOUNG SISTER I F...,MY FAMILY SMALL MOTHER FATHER YOUNG WIFE I FIN...,"My family is small. It consists of my mother, ...",SISTER,WIFE
1,1,0.167,6,My family has a total of six grandchildren.,MY FAMILY HAVE TOTAL SIX GRANDCHILDREN,MY FAMILY HAVE TOTAL PERFECT GRANDCHILDREN,My family has a total of perfect grandchildren.,SIX,PERFECT
2,1,0.091,11,My family recently moved to New York City beca...,FAMILY MOVE RECENT WHERE NYC WHY FATHER THERE ...,CLASS MOVE RECENT WHERE NYC WHY FATHER THERE W...,My class recently moved in New York City becau...,FAMILY,CLASS
3,1,0.000,3,We are fine with the family moving.,FAMILY MOVE WE FINE,FAMILY MOVE WE FINE,"My family moved, and we are fine.",NaN,NaN
4,1,0.077,13,My family vacation every year is in Florida be...,MY FAMILY VACATION TOGETHER EVERY-YEAR WHERE T...,MY CLASS VACATION TOGETHER EVERY-YEAR WHERE TH...,My class goes on vacation together every year ...,FAMILY,CLASS

In [3]:
condition = 1
cond_data = data[data["condition"] == condition]

cond_data.head()

,condition,wer,num_signgloss,intended_meaning,asl_gloss,error_asl_gloss,error_intended_meaning,original_word,misclassified_word
0,1,0.111,9,"My family is small. It consists of my mother, ...",MY FAMILY SMALL MOTHER FATHER YOUNG SISTER I F...,MY FAMILY SMALL MOTHER FATHER YOUNG WIFE I FIN...,"My family is small. It consists of my mother, ...",SISTER,WIFE
1,1,0.167,6,My family has a total of six grandchildren.,MY FAMILY HAVE TOTAL SIX GRANDCHILDREN,MY FAMILY HAVE TOTAL PERFECT GRANDCHILDREN,My family has a total of perfect grandchildren.,SIX,PERFECT
2,1,0.091,11,My family recently moved to New York City beca...,FAMILY MOVE RECENT WHERE NYC WHY FATHER THERE ...,CLASS MOVE RECENT WHERE NYC WHY FATHER THERE W...,My class recently moved in New York City becau...,FAMILY,CLASS
3,1,0.000,3,We are fine with the family moving.,FAMILY MOVE WE FINE,FAMILY MOVE WE FINE,"My family moved, and we are fine.",NaN,NaN
4,1,0.077,13,My family vacation every year is in Florida be...,MY FAMILY VACATION TOGETHER EVERY-YEAR WHERE T...,MY CLASS VACATION TOGETHER EVERY-YEAR WHERE TH...,My class goes on vacation together every year ...,FAMILY,CLASS

In [7]:
index = 1
row = cond_data.iloc[index]
row["intended_meaning"]

'My family has a total of six grandchildren.'

In [7]:
conditions_used = [3, 5, 9]
form_factors = ["glasses", "glasses + glove", "glasses + ring", "glasses + wristband"]
incomplete_conditions = [(c, f) for c in conditions_used for f in form_factors]

In [8]:
incomplete_conditions.remove((3, "glasses"))
incomplete_conditions

[(3, 'glasses + glove'),
 (3, 'glasses + ring'),
 (3, 'glasses + wristband'),
 (5, 'glasses'),
 (5, 'glasses + glove'),
 (5, 'glasses + ring'),
 (5, 'glasses + wristband'),
 (9, 'glasses'),
 (9, 'glasses + glove'),
 (9, 'glasses + ring'),
 (9, 'glasses + wristband')]